### ISSUE TITLE
ebuild for bobcat fails to build with 'template argument deduction/substitution failed'

### ISSUE THREAD

**Issue by DrItanium** [jdm64/saphyr#1]
Looks like gentoo with gcc 4.8.4 does not like the bobcat lib. I haven't tried upgrading to gcc 4.9.3 (5.1 and 5.2 are not even marked as unstable). 

I'm going to try clang 3.5.0 and see if it works manually.

**Comment by DrItanium** [comment]
correction, gcc 4.7.4

**Comment by DrItanium** [comment]
nope on gcc 4.7.4

**Comment by DrItanium** [comment]
emerging gcc 4.9.3 and going to try that

**Comment by DrItanium** [comment]
no for gcc 4.9.3 as well

**Comment by DrItanium** [comment]
It works if I compile it manually with std=c++14 via the build command

**Comment by jdm64** [comment]
That's right. Looking in my make.conf file I have -std=c++14 added to my CXXFLAGS. I'll see if I can add that to the ebuild. I might have also added -pthread to the LDFLAGS. what is the typical LDFLAGS?

**Comment by jdm64** [comment]
I've updated the ebuilds and added an ebuild for saphyr which will install all required dependencies and the saphyr binary. It should compile on g++ 4.8. If you can confirm this then I will merge ebuild into master.

**Comment by DrItanium** [comment]
Bobcat is now succesfully compiling with gcc 4.9.3 with std=c++1y. It only build with one core but looking the build script I don't see an easy way of fixing that. So I'm considering this issue closed. Now I can try flexc++ and bisonc++
