### ISSUE TITLE
AppImage for download?

### ISSUE THREAD

**Issue by probonopd** [jdm64/saphyr#13]
https://github.com/jdm64/saphyr/blob/9daae2a4f9e2104144f820db94d3a1db45e55750/scripts/buildAppImage-create.sh#L4

It would be great if the resulting AppImage was available on GitHub Releases. It can be produced e.g., using Travis CI and uploaded using something like [uploadtool](https://github.com/probonopd/uploadtool). Thanks!

**Comment by jdm64** [comment]
Do you just monitor all references to AppImage on github? How'd you find this repo?

The AppImage is now being published. Although, it takes about 2.5 sec to mount/exec since it's so large (~20MB). Not very good for a command line tool.

**Comment by probonopd** [comment]
```
me@host:~$ time Downloads/saphyr-x86_64.AppImage 
no input file provided

real	0m1.571s
user	0m0.008s
sys	0m0.017s
```

on an Intel Core2 Duo E8400 from 10 years ago(!)

**Comment by probonopd** [comment]
Does the result change if you provide an absolute path to the input file? 

To see how it performs without the mounting of the AppImage:

```
me@host ~ $ Downloads/saphyr-x86_64.AppImage --appimage-extra

me@host ~ $ time squashfs-root/AppRun
no input file provided

real	0m0.015s
user	0m0.008s
sys	0m0.008s
```

And we can simplify things:

```
me@host ~ $ patchelf --set-rpath '$ORIGIN/../lib' squashfs-root/usr/bin/saphyr

me@host ~ $ ( cd squashfs-root/ ; rm AppRun ; ln -s usr/bin/saphyr AppRun 

me@host ~ $ time squashfs-root/AppRun
no input file provided

real	0m0.013s
user	0m0.004s
sys	0m0.008s
```

**Comment by jdm64** [comment]
Providing an absolute path didn't help, but using a symlink for AppRun fixed the performance issue.

But now the built AppImage isn't loading the shared libraries correctly. Patchelf isn't available on ubuntu trusty and chrpath fails with `no rpath or runpath tag found`.

Do you know a good place to download a copy of patchelf that works with trusty?

**Comment by probonopd** [comment]
Mounting a filesystem takes some time. But I assume that in real-life use cases the overhead of mounting is not that high, since the bulk of time will be spent in computation while the filesystem stays mounted - correct?

**Comment by jdm64** [comment]
I don't expect compile times to be longer than a few seconds in the worst case scenario, so 1.7 sec is a large percentage of the time. Also when the compiler is used as part of a make job to compile one file at a time the mount times will compound.

But if you think that I'm using AppImage correctly/performantly and this isn't a bug, then the performance is fine for now. I'll probably build a deb/rpm at some point, but for now AppImage was dead easy to create!

**Comment by probonopd** [comment]
Does not run on Ubuntu 14.04:

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/c7436251f4b2b241d424c753aba17f666e5131b1/database/saphyr/screenshot.png)

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems.

**Comment by jdm64** [comment]
Should be fixed now. LLVM 6 links to a newer libstdc++, so switched the appimage build to llvm 4.

**Comment by probonopd** [comment]
Thank you, it is working for me now.
